[build]
  # ビルドコマンド
  command = "npm run build"
  # 公開ディレクトリ
  publish = ".next"
  # 関数ディレクトリ
  functions = ".netlify/functions"

# Next.js用の特殊設定
[build.environment]
  # Next.jsの変数
  NEXT_TELEMETRY_DISABLED = "1"
  # Node.jsバージョン
  NODE_VERSION = "18"
  # Canvas依存関係のための環境変数
  LD_LIBRARY_PATH = "/usr/lib64-nvidia"
  LD_PRELOAD = ""

# PRプレビュー設定
[context.deploy-preview]
  command = "npm run build"
  publish = ".next"

# プラグイン設定
[[plugins]]
  package = "@netlify/plugin-nextjs"

# リダイレクト設定（Next.jsが自動的に処理するため少なくて済む）
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# ヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' *.netlify.app; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' *.googleapis.com; frame-ancestors 'none';"

# API画像ルートの特殊設定
[[headers]]
  for = "/api/og-image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"